sudo: required
services:
  - docker

before_install:
  - docker build -t cr9ver/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cr9ver/react-test npm test

after_sucess:
  - docker build -t cr9ver/multi-client ./client
  - docker build -t cr9ver/multi-nginx ./nginx
  - docker build -t cr9ver/multi-server ./server
  - docker build -t cr9ver/multi-worker ./worker

